apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  labels:
    app: node
    demo: helm
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: node
      demo: helm
  template:
    metadata:
      labels:
        app: node
        demo: helm
    spec:
      containers:
      - name: node
        image: "openjdk:{{ .Values.deployment.imageVersion }}"
        ports:
        - containerPort: 80